blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.Postlist.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail' ),
    path('contact', views.contact_form, name='contact'),
    path('signup', views.signup, name='signup')
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS = (
    (0, 'draft'),
    (1, 'publish')
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique = True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'blog_post')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices = STATUS, default=0)


    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

def should_be_empty(value):
    if value:
        raise forms.ValidationError('Field is not empty...!')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=80)
    message = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput,
        label="Leave empty", validators=[should_be_empty])

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True, label='email', error_messages={'exists':'This already exists.'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    def clean_emai(self):
        if User.objects.filter(email=self.clean_data['email']).exists():
            raise forms.ValidationError(self.fields['email'].error_message['exists'])
        return self.clean_data['email']

blog/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from .models import Post
from .forms import ContactForm

from .forms import UserCreateForm


class Postlist(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/index.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


def contact_form(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = f'Message from {form.cleaned_data["name"]}'
            message = form.cleaned_data["message"]
            from_email = form.cleaned_data["email"]
            recipient_list = ["jc23678@gmail.com.com"]
            send_mail(subject, message, from_email, recipient_list, fail_silently=False)
            try:
                send_mail(subject, message, from_email, recipient_list, fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Invalid Header found')
            return HttpResponse('Success...Your email has been sent')
    return render(request, 'blog/contact.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, new_user)
            return redirect('home')
    else:
        form = UserCreateForm()
    return render(request, 'registration/signup.html', {'form': form})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapi.com/css?family=Robot:400,700" rel="stylesheet">
    <meta name="google" content="notranslate"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <title>JChaudhary Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <style>
        body{
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;

        }

        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #3398E1;
            color: white;
            text-align: center;
        }

        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }

        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }

        .masthead{
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px
        }




    </style>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-light bg-light shadow" id="mainNav">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">JChaudhary Blogs</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">About</a>
                        </li>
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Policy</a>
                        </li>
                    {% if user.is_authenticated %}
                         <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'login' %}">Sign In</a>
                        </li>
                        {% endif %}

                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'contact' %}">Contact</a>
                        </li>
                </ul>
            </div>
        </div>
    </nav>


    {% block content %}
     <!--Content Goes Here-->
    {% endblock content%}



    <footer class="footer py-0.25 bg-grey">
        <p class="m-0 text-dark text-center">Copyright &copy; Jignesh Chaudhary</p>
    </footer>
</body>
</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% block content %}
<style>
        .container{
             padding-top: 30px;
        }

    #id_name{
        width:100%
        }

    #id_message{
        width:100%
        }

    #id_email{
        width:100%
        }
</style>

<div class="container ">
    <h2>Send Me a Message</h2>
    <form action="" method="POST">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            <label>{{ field.label_tag }}</label>
            <p>{{ field }}</p>
        </div>
        {% endfor %}
        <button type="reset" class="btn btn-secondary">Reset</button>
         <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block content %}
    <style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text{
        color: white;
    }

    .card{
        box-shadow: 0 16px 48px #E3E7EB;
    }

</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">


                    <h3 class=" site-heading my-4 mt-3 text-white">
                     {% if user.is_authenticated %}
                        Welcome to JChaudhary's Blog {{ user.username }}
                        {% else %}
                        Welcome to JChaudhary's Blog
                        {% endif %}
                    </h3>
                    <p class="text-light">I love to code...hope u do too as well!!! &nbsp </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3 left top">
            <div class="card-body">
                <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
                <p class="text-muted"> {{ post.author }} | {{ post.created_on }} </p>
                <p class="card-text"> {{ object.content }}</p>
            </div>
        </div>

        {% block sidebar %} {% include 'blog/sidebar.html' %} {% endblock sidebar %}
    </div>
</div>

{% endblock content %}

blog/templates/blog/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }

</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> Built with Django!</p>
        <a href="https://www.facebook.com/chaudharyjignesh"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}